### ISSUE TITLE
Define an auto-correct library

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#10]
### Description
Develop a library used for word correction. 

__Input:__ A string representing a word
__Output:__ A list containing the input word, if the word is a valid English word; else, a list containing English words that are similar to the input word, along with their score. The score might be calculated heuristically by taking into account factors like:
* the degree of similarity to the input word
* aggregated word correction data from an external source (e.g. supervised learning)

### Suggestions
Investigate the possibility of using PyEnchant (https://pythonhosted.org/pyenchant/) to accomplish the desired results.

See http://norvig.com/ngrams/spell-errors.txt for some common typing errors and their correct counterpart.

**Comment by ovidiupw** [comment]
Closing as completed.

**Comment by LucianOnicescu** [comment]
autocorrect.py - Python script for identifying language errors and suggesting a correction

Uses pyenchant (http://pythonhosted.org/pyenchant/) and wordfreq (https://pypi.python.org/pypi/wordfreq) modules
For each unknown word (typo) a list of possible corrections is generated. The most common English word is selected and the sentence is remade.
