### ISSUE TITLE
Use nltk to construct a syntactic tree represented by an xml dom, given a raw input text

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#2]
Points to consider:
* the name of the root tag of the resulting xml should be _annotated-string_
* the name of the children of the root tag should be tags _sentence_
* the children of the sentences should be tags named _word_ (for words), _expression_ (for knwon non-word constructs, e.g. math expressions), _punctuation_ for punctuation marks, [others may come in here], or _unknown_ for unknown constructs
* all words must be validated with a dictionary to confirm their existence between including word inside _word_ tag
* each of the _word_ tags must contain the following attributes:
  * synonyms="s1,s2,s3", for non proper words
  * definitions="d1,d2,d3" for non proper words
  * description="$d" for proper words
  * description-source="$link" for proper words
* all tokenized morphological constructs must be annotated with some tag, including question marks, commas etc.
* any error resulting in the parsing of the raw input string or other failure points should result in an explicit Exception thrown that should include a message of the root cause of the exception. Try to define custom exceptions for more granularity.
* resulting xml must be valid according to https://www.w3.org/TR/xml/

**Comment by ovidiupw** [comment]
First version in production. Supports synonyms, definitions, baseForm

**Comment by ovidiupw** [comment]
First version has a bug (index out of range). See http://ec2-52-213-135-23.eu-west-1.compute.amazonaws.com/api/v1/nltk/sentence-annotation?sentence=hello for more details.

**Comment by ovidiupw** [comment]
I fixed the bug. Closing as complete.

**Comment by alex17111995** [comment]
The module constructs an XML tree. the root contains a list of sentences. Each sentence has a list of the words in the sentence. Each word has its definitions and synonyms, base form and part of speech. This is done using the nltk module. Also integrates with the anaphora resolution, Adrian Butnaru's module and with Alex Rusu's module, which corrects a sentence.  Writing the XML is done using the python module xml.etree
