### ISSUE TITLE
Define an interface to transpose the result of the construction process into a json response

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#3]
Points to consider:
* ouput json must conform to the response schema defined at https://github.com/ovidiupw/ChatbotTextProcessing/blob/master/README.md#5-artifficial-intelligence-communication-interface-uses-http-requests
* all exceptions coming from xml construction process must be handled, associated with an error code and mapped to the corresponding fields in the json response (according to the schema defined above)

**Comment by CiucT** [comment]
Made the objectResponse conform the response schema defined at https://github.com/ovidiupw/ChatbotTextProcessing/blob/master/README.md#5-artifficial-intelligence-communication-interface-uses-http-requests and convert it into a json string.

**Comment by ovidiupw** [comment]
Closing as this is already implemented in production
