### ISSUE TITLE
Post-process text to be sent back to chat-bot user

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#5]
Given some string representation of a sentence, proofread it, annotate it via XML and provide a clean, __natural__, final version of the sentence to be sent back to the user of the chat-bot.

Define an XML schema (documentation) for the resulting XML tags / annotations.

### Random choice, variable responses for empty input strings
Choose a random response for empty input strings

* __sentence__ = ""
* __post-processed sentence__ = 
```xml
<sentence>
  <raw>I don't know what to say</raw>
  <annotated>I don't know what to say</annotated>
<sentence>
```

### Beautifying abstract answers
* __sentece__ = "abc"
* __post-processed sentence__ = 
```xml
<sentence>
  <raw>My guts tell me that the answer to that is "abc"</raw>
  <annotated>
    My guts tell me that the answer to that is 
    <raw-bot-output>"abc"</raw-bot-output>
  </annotated>
</sentence> - 
```
_"abc" didn't exist in dictionary so we tried to beautify the response to sound more natural, as if it came from a human being_

### Input error correction 
* __sentence__ = "Its cold outside"
* __post-processed-sentence__ = 
```xml
<sentence>
  <raw> It's cold outside</raw>
  <annotated> It's cold outside</annotated>
</sentence> 
```
_Using an advanced string comparison might work, calculating distances between strings and providing output based on strings closest to matched string_

### Proper names referencing
* __sentence__ = "The weather in Iasi is beautiful"
* __post-processed sentence__ = 
```xml
<sentence>
  <annotated>
    The weather in 
    <link ref="https://wiki/iasi">
      Iasi
    </link>
    is beautiful 
  </annotated>
  <raw>The weather in Iasi is beautiful</raw>
</sentence>
```

### Aggressive or bad vocabulary replacement by random safe responses
Avoid accidental bad or insulting vocabulary to reach the end-user of the chat-bot.

* __sentence__ = "Go to hell"
* __post-processed sentence__ = 
```xml
<sentence>
  <raw>I will not answer to that</raw>
  <annotated>I will not answer to that</annotated>
</sentence>
```

**Comment by ovidiupw** [comment]
"__Input error correction__" is an important part of this task. Investigate the possibility of using PyEnchant (https://pythonhosted.org/pyenchant/) to accomplish the desired results.

**Comment by ovidiupw** [comment]
See http://norvig.com/ngrams/spell-errors.txt for some common typing errors and their correct counterpart.

**Comment by cristiDorneanu** [comment]
Given some string representation of a sentence, this module annotates it via XML to provide a clean, natural, final version of the sentence to be sent back to the user of the chat-box.
In given situations (empty sentence, unknown words) it provides a natural, annotated answer, randomly selected (a list of possible answers is needed) from a list of possible answers.
In case that the sentence is an empty string, it provides an answer that sounds natural, as if it came from a human being.
In case of unknown words, it annotates the words with proper tags, and provides an answer to the user. This is done using the nltk library.
In case of proper names referencing, it annotates the words and provides a link to a wiki page. This was done using nltk library.
In case of aggressive or bad vocabulary, it prevents accidental bad or insulting vocabulary to reach the end-user of the chat-bot. This is done using the profanity library.
