### ISSUE TITLE
Sentence keyword resolution

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#9]
### Description
One way of defining keywords in a sentence is to count the number of the occurrences of a word in a text and deduce, by that number, whether the word might be a keyword.

Identify keywords in a supplied XML annotated sentence and annotate them accordingly.

### Suggestions
* __sentence:__ the XML representation of "Ana are multe mere, dar ii este frica sa manance merele fiindca au viermi"
* __annotated sentence:__ "<.... <word occurences="2">mere</word>....>"

**Comment by CiucT** [comment]
implemented a keyword probability finder and extractor using rake .Documetation for rake can be find at https://www.airpair.com/nlp/keyword-extraction-tutorial

**Comment by ovidiupw** [comment]
Closing as completed
